### ISSUE TITLE
bug report #1: Неверное отображения числа пересдач

### ISSUE THREAD

**Issue by igoryan75** [Kaydaas/mpei-os-labs#1]
**Условия выполнения:**
Вывод минимальных пересдач при условии, что у всех студентов (3) одинаковое число пересдач (10)

**Результат:**
Студенты с мнимальным количеством пересдач (**_0_**) в группе A-09-17:
GromovMN
VlasovaOM
ZagainovaMD

**Ожидаемый результат:**
Студенты с мнимальным количеством пересдач (**_10_**) в группе A-09-17:
GromovMN
VlasovaOM
ZagainovaMD

**Comment by Kaydaas** [comment]
При каких входных данных это происходит?

**Comment by Kaydaas** [comment]
Исправлено

**Comment by Kaydaas** [comment]
Исправлено
