### ISSUE TITLE
bug report #2: Некорректное сообщение при отсутствии пересдач 

### ISSUE THREAD

**Issue by igoryan75** [Kaydaas/mpei-os-labs#2]
**Условия выполнения:**
Запуск скрипта когда у студентов (9) нет пересдач

**Результат:**
Студенты с мнимальным количеством пересдач () в группе A-09-17

**Ожидаемый результат:**
Не найдено студентов с пересдачами

**Comment by Kaydaas** [comment]
Исправлено
