### ISSUE TITLE
bug report #3: Некорректное сообщение при работе с пустыми файлами

### ISSUE THREAD

**Issue by igoryan75** [Kaydaas/mpei-os-labs#3]
**Условия выполнения:**
Оставить содержимое файлов TEST-* пустым

**Результат:**
Студенты с минимальным количеством пересдач () в группе A-06-04:

**Ожидаемый результат:**
Не найдено студентов с пересдачами

**Comment by Kaydaas** [comment]
Добавлена проверка на отсутствие пересдач
