### ISSUE TITLE
bug report #4: Некорректное сообщение при отсутствии рабочих файлов

### ISSUE THREAD

**Issue by igoryan75** [Kaydaas/mpei-os-labs#4]
**Условия выполнения:**
Отсутствие файлов TEST-* в директории \mpei-os-labs\lab4\*\tests

**Результат:**
grep: ./Криптозоология/tests/*: No such file or directory
Студенты с мнимальным количеством пересдач () в группе A-06-04:

**Ожидаемый результат:**
Файлы не найдены

**Comment by Kaydaas** [comment]
Добавлена функция check_if_tests_exist для проверки наличия файлов с тестами
