### ISSUE TITLE
Чек-лист после тестирования №1

### ISSUE THREAD

**Issue by igoryan75** [Kaydaas/mpei-os-labs#5]
Обозначения:
Зелёный - положительные тесты
Красный - негативные тесты (нестандартные ситуции)
Жёлтый - обратить ВНИМАНИЕ на тест, либо он не пройден, либо есть предложение по доработке.

Сверху справа листа написано к какой конкретно функции относится тот или иной тест

[OS LAB4 CHECK-LIST.pdf](https://github.com/Kaydaas/mpei-os-labs/files/13268978/OS.LAB4.CHECK-LIST.pdf)

**Comment by Kaydaas** [comment]
Исправлено: https://github.com/Kaydaas/mpei-os-labs/commit/0c6afb57bc553e90198b1eec5003f21b5d51c8f4
