### ISSUE TITLE
Чек-лист после тестирования #2

### ISSUE THREAD

**Issue by igoryan75** [Kaydaas/mpei-os-labs#6]
Обозначения:
Зелёный - положительные тесты
Красный - негативные тесты (нестандартные ситуции)
Жёлтый - обратить ВНИМАНИЕ на тест, либо он не пройден, либо есть предложение по доработке.

Сверху справа листа написано к какой конкретно функции относится тот или иной тест

[OS LAB4 CHECK-LIST2.pdf](https://github.com/Kaydaas/mpei-os-labs/files/13339550/OS.LAB4.CHECK-LIST2.pdf)

**Comment by Kaydaas** [comment]
Исправлено: https://github.com/Kaydaas/mpei-os-labs/commit/1963610a508cf26df219a2d6e78faf91a171e3df
